- name: 1.1.4 Configure /var/tmp
  block: 
  - name: 1.1.4.2 Ensure noexec option set on /var/tmp partition
    block:
      - name: Check if noexec option is set on /var/tmp partition
        shell: findmnt --kernel /var/tmp | grep noexec
        register: audit_output
        failed_when: "audit_output.rc == 2"
        check_mode: no

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.4.2 | {{ compliance_status }}"


  - name: 1.1.4.3 Ensure nosuid option set on /var/tmp partition
    block:
      - name: Check if nosuid option is set on /var/tmp partition
        shell: findmnt --kernel /var/tmp | grep nosuid
        register: audit_output
        failed_when: "audit_output.rc == 2"
        check_mode: no

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.4.3 | {{ compliance_status }}"


  - name: 1.1.4.4 Ensure nodev option set on /var/tmp partition
    block:
      - name: Check if nodev option is set on /var/tmp partition
        shell: findmnt --kernel /var/tmp | grep nodev
        register: audit_output
        failed_when: "audit_output.rc == 2"
        check_mode: no

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.4.4 | {{ compliance_status }}"




