- name: 1.1.8 Configure /dev/shm
  block: 
  - name: 1.1.8.1 Ensure /dev/shm is a separate partition
    block:
      - name: Check if /dev/shm is mounted
        shell: findmnt --kernel /dev/shm
        register: audit_output
        ignore_errors: yes

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.8.1 | {{ compliance_status }}"


  - name: 1.1.8.2 Ensure nodev option set on /dev/shm partition
    block:
      - name: Check if nodev option is set on /dev/shm partition
        shell: findmnt --kernel /dev/shm | grep nodev
        register: audit_output
        failed_when: "audit_output.rc == 2"
        check_mode: no

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.8.2 | {{ compliance_status }}"


  - name: 1.1.8.3 Ensure noexec option set on /dev/shm partition
    block:
      - name: Check if noexec option is set on /dev/shm partition
        shell: findmnt --kernel /dev/shm | grep noexec
        register: audit_output
        failed_when: "audit_output.rc == 2"
        check_mode: no

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.8.3 | {{ compliance_status }}"


  - name: 1.1.8.4 Ensure nosuid option set on /dev/shm partition
    block:
      - name: Check if nosuid option is set on /dev/shm partition
        shell: findmnt --kernel /dev/shm | grep nosuid
        register: audit_output
        failed_when: "audit_output.rc == 2"
        check_mode: no

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.8.4 | {{ compliance_status }}"

