- name: 1.1.2 Configure /tmp
  block: 
  - name: 1.1.2.1 Ensure /tmp is a separate partition
    block:
      - name: Check if /tmp is mounted
        shell: findmnt --kernel /tmp | cat
        register: audit_output
 
      - name: Set compliance status
        set_fact:
          compliance_status: "Not Compliant"
        when: audit_output.stdout == ""

      - name: Check if /tmp is mounted on startup
        shell: systemctl is-enabled tmp.mount
        register: systemctl_output
        when: audit_output.stdout != ""

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Not Compliant' if systemctl_output.stdout.strip() == 'disabled' else 'Compliant' }}"
        when: audit_output.stdout != ""

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.2.1 | {{ compliance_status }}"


  - name: 1.1.2.2 Ensure nodev option set on /tmp partition
    block:
      - name: Check if nodev option is set on /tmp partition
        shell: findmnt --kernel /tmp | grep nodev
        register: audit_output
        failed_when: "audit_output.rc == 2"
        check_mode: no

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.2.2 | {{ compliance_status }}"


  - name: 1.1.2.3 Ensure noexec option set on /tmp partition
    block:
      - name: Check if noexec option is set on /tmp partition
        shell: findmnt --kernel /tmp | grep noexec
        register: audit_output
        failed_when: "audit_output.rc == 2"
        check_mode: no

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.2.3 | {{ compliance_status }}"


  - name: 1.1.2.4 Ensure nosuid option set on /tmp partition
    block:
      - name: Check if nosuid option is set on /tmp partition
        shell: findmnt --kernel /tmp | grep nosuid
        register: audit_output
        failed_when: "audit_output.rc == 2"
        check_mode: no

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if output.stdout != '' else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.1.2.4 | {{ compliance_status }}"

