- name: Filesystem Integrity Checking
  block:
    - name: 1.3.1 Ensure AIDE is installed
      block:
        - name: Check if AIDE is installed
          shell: rpm -q aide
          register: output
          failed_when: output.stdout == ''
          changed_when: false
      
        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Not Compliant' if output.rc == 1 else 'Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.3.1 | {{ compliance_status }}"


    - name: 1.3.2 Ensure filesystem integrity is regularly checked
      when: output.rc != 1
      block:
        - name: Verify aidcheck.service is enabled
          systemd:
            name: aidcheck.service
            enabled: yes
          register: aidcheck_service

        - name: Verify aidcheck.timer is enabled
          systemd:
            name: aidcheck.timer
            enabled: yes
          register: aidcheck_timer

        - name: Verify aidcheck.timer is running
          systemd:
            name: aidcheck.timer
            state: started
          register: aidcheck_timer_running

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if (aidcheck_service.state == 'enabled') and (aidcheck_timer.state == 'enabled') and (aidcheck_timer_running.state == 'running') else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.3.2 | {{ compliance_status }}"


    - name: 1.3.3 Ensure cryptographic mechanisms are used to protect the integrity of audit tools
      block: 
        - name: Copy audit script to host
          copy:
            src: "scripts/1_3_3"
            dest: "/tmp/audit/1_3_3"
            mode: '0755'

        - name: Remove carriage return characters from the audit script
          shell: sed -i 's/\r$//' /tmp/audit/1_3_3

        - name: Run audit script
          shell: /tmp/audit/1_3_3
          register: audit_output 

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if 'PASS' in audit_output.stdout else 'Not Compliant' if 'FAIL' in audit_output.stdout else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.3.3 | {{ compliance_status }}"