- name: Secure Boot Settings
  block: 
    - name: 1.4.1 Ensure bootloader password is set
      block:
      - name: Check grub password
        shell: awk -F. '/^\s*GRUB2_PASSWORD/ {print $1"."$2"."$3}' /boot/grub2/user.cfg | cat
        register: output

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if 'GRUB2_PASSWORD=grub.pbkdf2.sha512' in output.stdout else 'Not Compliant' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.4.1 | {{ compliance_status }}"
      

    - name: 1.4.2 Ensure permissions on bootloader config are configured
      block:
        - name: Copy audit script to host
          copy:
            src: "scripts/1_4_2"
            dest: "/tmp/audit/1_4_2"
            mode: '0755'

        - name: Remove carriage return characters from the audit script
          shell: sed -i 's/\r$//' /tmp/audit/1_4_2

        - name: Run audit script
          shell: /tmp/audit/1_4_2
          register: audit_output 

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if 'PASS' in audit_output.stdout else 'Not Compliant' if 'FAIL' in audit_output.stdout else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.4.2 | {{ compliance_status }}"
            result: "### 1.4.2 \n```{{ audit_output.stdout }}\n```\n"





