- name: Additional Process Hardening
  block: 
  - name: 1.5.1 Ensure core dump storage is disabled
    block:
    - name: Check coredump conf
      shell: grep -i '^\s*storage\s*=\s*none' /etc/systemd/coredump.conf | cat
      register: output

    - name: Set compliance status
      set_fact:
        compliance_status: "{{ 'Compliant' if 'Storage=none' in output.stdout else 'Not Compliant' }}"
    
    - name: Log to file
      include_tasks: ../logging.yml
      vars:
        status: "1.5.1 | {{ compliance_status }}"
   

  - name: 1.5.2 Ensure core dump backtraces are disabled   
    block:
      - name: Check coredump conf
        shell: |
          grep -Pi '^\h*ProcessSizeMax\h*=\h*0\b' /etc/systemd/coredump.conf || echo -e "\n- Audit results:\n ** Fail **\n - \"ProcessSizeMax\" is: \"$(grep -i 'ProcessSizeMax' /etc/systemd/coredump.conf)\""
        register: output
      
      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Not Compliant' if 'Fail' in output.stdout else 'Compliant' }}"
    
      - name: Log to file
        include_tasks: ../logging.yml
        vars:
         status: "1.5.2 | {{ compliance_status }}"
   

  - name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled
    block:
      - name: Copy audit script to host
        copy:
          src: "scripts/1_5_3"
          dest: "/tmp/audit/1_5_3"
          mode: '0755'

      - name: Remove carriage return characters from the audit script
        shell: sed -i 's/\r$//' /tmp/audit/1_5_3

      - name: Run audit script
        shell: /tmp/audit/1_5_3
        register: audit_output 

      - name: Set compliance status
        set_fact:
          compliance_status: "{{ 'Compliant' if 'PASS' in audit_output.stdout else 'Not Compliant' if 'FAIL' in audit_output.stdout else 'Unknown' }}"

      - name: Log to file
        include_tasks: ../logging.yml
        vars:
          status: "1.5.3 | {{ compliance_status }}"
          result: "### 1.5.3 \n```{{ audit_output.stdout }}\n```\n"

