- name: Configure SELinux
  block:
    - name: 1.6.1.1 Ensure SELinux is installed
      block:
        - name: Check if SELinux is installed
          shell: rpm -q libselinux
          register: output
          failed_when: output.stdout == ''
          changed_when: false
      
        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Not Compliant' if output.stdout == 'package libselinux is not installed'  else 'Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.6.1.1 | {{ compliance_status }}"


    - name: 1.6.1.2 Ensure SELinux is not disabled in bootloader configuration
      block: 
        - name: Check SELinux status in bootloader configuration
          shell: grubby --info=ALL | grep -Po '(selinux|enforcing)=0\b'
          register: output
          failed_when: output.rc == 2
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if output.stdout == '' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.6.1.2 | {{ compliance_status }}"
 

    - name: 1.6.1.3 Ensure SELinux policy is configured
      block:
        - name: Check SELinux configuration file
          shell: grep -E '^\s*SELINUXTYPE=(targeted|mls)\b' /etc/selinux/config
          register: config_output

        - name: Check SEStatus
          shell: sestatus | grep Loaded
          register: sestatus_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if ('targeted' in config_output.stdout or 'mls' in config_output.stdout) and ('targeted' in sestatus_output.stdout or 'mls' in sestatus_output.stdout)  else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.6.1.3 | {{ compliance_status }}"


    - name: 1.6.1.4 Ensure the SELinux mode is not disabled
      block:
        - name: Get SELinux's current mode 
          shell: getenforce
          register: getenforce_output

        - name: Get SELinux's configured mode
          shell: grep -Ei '^\s*SELINUX=(enforcing|permissive)' /etc/selinux/config
          register: config_output
          failed_when: config_output.rc == 2
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if ('Enforcing' in getenforce_output.stdout or 'Permissive' in getenforce_output.stdout) and (config_output != '')  else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.6.1.4 | {{ compliance_status }}"


    - name: 1.6.1.6 Ensure no unconfined services exist
      block: 
        - name: Check for unconfined services
          shell: ps -eZ | grep unconfined_services_t
          register: services_output
          failed_when: services_output.rc == 2
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if services_output.stdout == ''  else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.6.1.6 | {{ compliance_status }}"
 

    - name: 1.6.1.7 Ensure SETroubleshoot is not installed
      block:
        - name: Check if setroubleshoot package is installed
          shell: rpm -q setroubleshoot
          register: output
          failed_when: output.rc == 2
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if output.stdout == 'package setroubleshoot is not installed'  else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.6.1.7 | {{ compliance_status }}"
 

    - name: 1.6.1.8 Ensure the MCS Translation Service (mcstrans) is not installed
      block:
        - name: Check if mcstrans package is installed
          shell: rpm -q mcstrans
          register: output
          failed_when: output.rc == 2
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if output.stdout == 'package mcstrans is not installed'  else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "1.6.1.8 | {{ compliance_status }}"
 