- name: Service Clients
  block:
    - name: 2.3.1 Ensure telnet client is not installed
      block:  
        - name: Check if telnet is installed
          shell: rpm -q telnet
          register: output
          failed_when: output.stdout == ''
          changed_when: false
      
        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if output.stdout == 'package telnet is not installed' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "2.3.1 | {{ compliance_status }}"

    - name: 2.3.2 Ensure LDAP client is not installed
      block:  
        - name: Check if openldap-clients is installed
          shell: rpm -q openldap-clients
          register: output
          failed_when: output.stdout == ''
          changed_when: false
      
        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if output.stdout == 'package openldap-clients is not installed' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "2.3.2 | {{ compliance_status }}"

    - name: 2.3.3 Ensure TFTP client is not installed
      block:  
        - name: Check if tftp is installed
          shell: rpm -q tftp
          register: output
          failed_when: output.stdout == ''
          changed_when: false
      
        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if output.stdout == 'package tftp is not installed' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "2.3.3 | {{ compliance_status }}"

    - name: 2.3.4 Ensure FTP client is not installed
      block:  
        - name: Check if ftp is installed
          shell: rpm -q ftp
          register: output
          failed_when: output.stdout == ''
          changed_when: false
      
        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if output.stdout == 'package ftp is not installed' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "2.3.4 | {{ compliance_status }}"