- name: Disable unused network protocols and devices
  block:
    - name: 3.1.2 Ensure wireless interfaces are disabled
      block: 
        - name: Copy audit script to host
          copy:
            src: "scripts/3_1_2"
            dest: "/tmp/audit/3_1_2"
            mode: '0755'

        - name: Remove carriage return characters from the audit script
          shell: sed -i 's/\r$//' /tmp/audit/3_1_2

        - name: Run audit script
          shell: /tmp/audit/3_1_2
          register: audit_output 

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if 'PASS' in audit_output.stdout else 'Not Compliant' if 'FAIL' in audit_output.stdout else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "3.1.2 | {{ compliance_status }}"       
            result: "### 3.1.2 \n```{{ audit_output.stdout }}\n```\n"
