- name: Configure rsyslog
  block:  
    - name: 4.2.1.1 Ensure rsyslog is installed
      block:
        - name: Check if rsyslog is installed
          shell: rpm -q rsyslog
          register: output
          failed_when: output.stdout == ''
          changed_when: false
      
        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Not Compliant' if output.stdout == 'package rsyslog is not installed'  else 'Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "4.2.1.1 | {{ compliance_status }}"

    - name: 4.2.1.2 Ensure rsyslog service is enabled
      block:
        - name: Check if rsyslog service is enabled
          shell: systemctl is-enabled rsyslog
          register: systemctl_output
          failed_when: systemctl_output.rc == 2
          changed_when: false
      
        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if systemctl_output.stdout == 'enabled' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "4.2.1.2 | {{ compliance_status }}"

    - name: 4.2.1.4 Ensure rsyslog default file permissions are configured
      block:
        - name: Copy audit script to host
          copy:
            src: "scripts/4_2_1_4"
            dest: "/tmp/audit/4_2_1_4"
            mode: '0755'

        - name: Remove carriage return characters from the audit script
          shell: sed -i 's/\r$//' /tmp/audit/4_2_1_4

        - name: Run audit script
          shell: /tmp/audit/4_2_1_4
          register: audit_output 

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if 'PASS' in audit_output.stdout else 'Not Compliant' if 'FAIL' in audit_output.stdout else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "4.2.1.4 | {{ compliance_status }}"

    - name: 4.2.1.7 Ensure rsyslog is not configured to receive logs from a remote client
      block:
        - name: Check if config files load the imtcp module
          shell: grep -Ps -- '^\h*module\(load="imtcp"\)' /etc/rsyslog.conf /etc/rsyslog.d/*.conf
          register: module_output
          failed_when: false
          changed_when: false

        - name: Check if config files allow imtcp input
          shell: grep -Ps -- '^\h*input\(type="imtcp" port="514"\)' /etc/rsyslog.conf /etc/rsyslog.d/*.conf
          register: input_output
          failed_when: false
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if module_output.stdout == '' and input_output.stdout == '' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "4.2.1.7 | {{ compliance_status }}"       