- name: Configure time-based job schedulers
  block:
    - name: 5.1.1 Ensure cron daemon is enabled
      block:
        - name: Check if crond is enabled
          shell: systemctl is-enabled crond
          register: systemctl_output
          failed_when: systemctl_output.rc == 2
          changed_when: false     

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if systemctl_output.stdout == 'enabled' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.1.1 | {{ compliance_status }}" 

    - name: 5.1.2 Ensure permissions on /etc/crontab are configured
      block: 
        - name: Get file attributes of /etc/crontab
          stat: 
            path: /etc/crontab
          register: crontab_stat

        - name: Verify file permissions, UID, and GID
          assert:
            that:
              - crontab_stat.stat.mode == '0600'
              - crontab_stat.stat.uid == 0
              - crontab_stat.stat.gid == 0
          register: compliance_check
          ignore_errors: yes

        - name: Set compliance status
          set_fact:
            compliance_status: "{% if compliance_check.failed %}Not Compliant{% else %}Compliant{% endif %}"
        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.1.2 | {{ compliance_status }}"

    - name: 5.1.3 Ensure permissions on /etc/cron.hourly are configured
      block: 
        - name: Get file attributes of /etc/cron.hourly
          stat: 
            path: /etc/cron.hourly
          register: cronhourly_stat

        - name: Verify file permissions, UID, and GID
          assert:
            that:
              - cronhourly_stat.stat.mode == '0700'
              - cronhourly_stat.stat.uid == 0
              - cronhourly_stat.stat.gid == 0
          register: compliance_check
          ignore_errors: yes

        - name: Set compliance status
          set_fact:
            compliance_status: "{% if compliance_check.failed %}Not Compliant{% else %}Compliant{% endif %}"
        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.1.3 | {{ compliance_status }}"

    - name: 5.1.4 Ensure permissions on /etc/cron.daily are configured
      block: 
        - name: Get file attributes of /etc/cron.daily
          stat: 
            path: /etc/cron.daily
          register: crondaily_stat

        - name: Verify file permissions, UID, and GID
          assert:
            that:
              - crondaily_stat.stat.mode == '0700'
              - crondaily_stat.stat.uid == 0
              - crondaily_stat.stat.gid == 0
          register: compliance_check
          ignore_errors: yes

        - name: Set compliance status
          set_fact:
            compliance_status: "{% if compliance_check.failed %}Not Compliant{% else %}Compliant{% endif %}"
        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.1.4 | {{ compliance_status }}"

    - name: 5.1.5 Ensure permissions on /etc/cron.weekly are configured
      block: 
        - name: Get file attributes of /etc/cron.weekly
          stat: 
            path: /etc/cron.weekly
          register: cronweekly_stat

        - name: Verify file permissions, UID, and GID
          assert:
            that:
              - cronweekly_stat.stat.mode == '0700'
              - cronweekly_stat.stat.uid == 0
              - cronweekly_stat.stat.gid == 0
          register: compliance_check
          ignore_errors: yes

        - name: Set compliance status
          set_fact:
            compliance_status: "{% if compliance_check.failed %}Not Compliant{% else %}Compliant{% endif %}"
        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.1.5 | {{ compliance_status }}"

    - name: 5.1.6 Ensure permissions on /etc/cron.monthly are configured
      block: 
        - name: Get file attributes of /etc/cron.monthly
          stat: 
            path: /etc/cron.monthly
          register: cronmonthly_stat

        - name: Verify file permissions, UID, and GID
          assert:
            that:
              - cronmonthly_stat.stat.mode == '0700'
              - cronmonthly_stat.stat.uid == 0
              - cronmonthly_stat.stat.gid == 0
          register: compliance_check
          ignore_errors: yes

        - name: Set compliance status
          set_fact:
            compliance_status: "{% if compliance_check.failed %}Not Compliant{% else %}Compliant{% endif %}"
        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.1.6 | {{ compliance_status }}"

    - name: 5.1.7 Ensure permissions on /etc/cron.d are configured
      block: 
        - name: Get file attributes of /etc/cron.d
          stat: 
            path: /etc/cron.d
          register: crond_stat

        - name: Verify file permissions, UID, and GID
          assert:
            that:
              - crond_stat.stat.mode == '0700'
              - crond_stat.stat.uid == 0
              - crond_stat.stat.gid == 0
          register: compliance_check
          ignore_errors: yes

        - name: Set compliance status
          set_fact:
            compliance_status: "{% if compliance_check.failed %}Not Compliant{% else %}Compliant{% endif %}"
        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.1.7 | {{ compliance_status }}"

    - name: 5.1.8 Ensure cron is restricted to authorized users
      block:
        - name: Copy audit script to host
          copy:
            src: "scripts/5_1_8"
            dest: "/tmp/audit/5_1_8"
            mode: '0755'

        - name: Remove carriage return characters from the audit script
          shell: sed -i 's/\r$//' /tmp/audit/5_1_8

        - name: Run audit script
          shell: /tmp/audit/5_1_8
          register: audit_output 

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if 'Pass' in audit_output.stdout else 'Not Compliant' if 'Fail' in audit_output.stdout else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.1.8 | {{ compliance_status }}" 
            result: "### 5.1.8 \n```\n{{ audit_output.stdout }}\n```\n"

    - name: 5.1.9 Ensure at is restricted to authorized users
      block:
        - name: Copy audit script to host
          copy:
            src: "scripts/5_1_9"
            dest: "/tmp/audit/5_1_9"
            mode: '0755'

        - name: Remove carriage return characters from the audit script
          shell: sed -i 's/\r$//' /tmp/audit/5_1_9

        - name: Run audit script
          shell: /tmp/audit/5_1_9
          register: audit_output 

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if 'Pass' in audit_output.stdout else 'Not Compliant' if 'Fail' in audit_output.stdout else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.1.9 | {{ compliance_status }}" 
            result: "### 5.1.9 \n```{{ audit_output.stdout }}\n```\n"



       