- name: User Accounts and Environment
  block:
    - name: 5.6.2 Ensure system accounts are secured
      block:
        - name: Check critical system accounts for nologin
          shell: | 
            awk -F: '($1!~/^(root|halt|sync|shutdown|nfsnobody)$/ && ($3<'"$(awk '/^\s*UID_MIN/{print $2}' /etc/login.defs)"' || $3 == 65534) && $7!~/^(\/usr)?\/sbin\/nologin$/) { print $1 }' /etc/passwd
          register: nologin_output
          failed_when: false
          changed_when: false

        - name: Ensure all accounts that configured the shell as nologin also have their passwords disabled.
          shell: | 
            awk -F: '/nologin/ {print $1}' /etc/passwd | xargs -I '{}' passwd -S '{}' | awk '($2!="L" && $2!="LK") {print $1}'
          register: passwd_output
          failed_when: false
          changed_when: false        

        - name: Set compliance status
          set_fact:
            compliance: "{{ 'Compliant' if nologin_output.stdout == '' and passwd_output.stdout == '' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.6.2 | {{ compliance_status }}"

    - name: 5.6.3 Ensure default user shell timeout is 900 seconds or less
      block:
        - name: Copy audit script to host
          copy:
            src: "scripts/5_6_3"
            dest: "/tmp/audit/5_6_3"
            mode: '0755'

        - name: Remove carriage return characters from the audit script
          shell: sed -i 's/\r$//' /tmp/audit/5_6_3

        - name: Run audit script
          shell: /tmp/audit/5_6_3
          register: audit_output 
          failed_when: false
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if 'PASSED' in audit_output.stdout else 'Not Compliant' if 'FAILED' in audit_output.stdout else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.6.3 | {{ compliance_status }}"
            result: "### 5.6.3 \n```{{ audit_output.stdout }}\n```\n"

    - name: 5.6.4 Ensure default group for the root account is GID 0
      block:
        - name: Check /etc/passwd
          shell: | 
            grep "^root:" /etc/passwd | cut -f4 -d:
          register: output
          failed_when: false
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if output.stdout == '0' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.6.4 | {{ compliance_status }}"

    - name: 5.6.5 Ensure default user umask is 027 or more restrictive
      block:
        - name: Copy audit script to host
          copy:
            src: "scripts/5_6_5"
            dest: "/tmp/audit/5_6_5"
            mode: '0755'

        - name: Remove carriage return characters from the audit script
          shell: sed -i 's/\r$//' /tmp/audit/5_6_5

        - name: Run audit script
          shell: /tmp/audit/5_6_5
          register: audit_output 
          failed_when: false
          changed_when: false

        - name: Check system wide umask
          shell: grep -RPi '(^|^[^#]*)\s*umask\s+([0-7][0-7][01][0-7]\b|[0-7][0-7][0-7][0-6]\b|[0-7][01][0-7]\b|[0-7][0-7][0-6]\b|(u=[rwx]{0,3},)?(g=[rwx]{0,3},)?o=[rwx]+\b|(u=[rwx]{1,3},)?g=[^rx]{1,3}(,o=[rwx]{0,3})?\b)' /etc/login.defs /etc/profile* /etc/bashrc*
          register: output
          failed_when: false
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if audit_output.stdout == 'Default user umask is set' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.6.5 | {{ compliance_status }}"

    - name: 5.6.6 Ensure root password is set
      block:
        - name: Check root password
          shell: passwd -S root
          register: output
          failed_when: false
          changed_when: false

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if 'Password set' in output.stdout else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "5.6.6 | {{ compliance_status }}"