- name: System File Permissions
  block: 
    - name: Copy stat-script to host
      copy:
        src: "scripts/stat-script"
        dest: "/tmp/audit/stat-script"
        mode: '0755'

    - name: Remove carriage return characters from the audit script
      shell: sed -i 's/\r$//' /tmp/audit/stat-script
  
    - name: 6.1.1 Ensure permissions on /etc/passwd are configured
      block:
        - name: Execute stat script on /etc/passwd
          shell: /tmp/audit/stat-script 644 /etc/passwd
          register: script_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if script_output.stdout == 'PASS' else 'Not Compliant' if script_output.stdout == 'FAIL' else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.1 | {{ compliance_status }} "
            result: "### 6.1.1 \n```{{ audit_output.stdout }}\n```\n"

    - name: 6.1.2 Ensure permissions on /etc/passwd- are configured
      block:
        - name: Execute stat script on /etc/passwd-
          shell: /tmp/audit/stat-script 644 /etc/passwd-
          register: script_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if script_output.stdout == 'PASS' else 'Not Compliant' if script_output.stdout == 'FAIL' else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.2 | {{ compliance_status }}"

    - name: 6.1.3 Ensure permissions on /etc/group are configured
      block:
        - name: Execute stat script on /etc/group
          shell: /tmp/audit/stat-script 644 /etc/group
          register: script_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if script_output.stdout == 'PASS' else 'Not Compliant' if script_output.stdout == 'FAIL' else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.3 | {{ compliance_status }}"

    - name: 6.1.4 Ensure permissions on /etc/group- are configured
      block:
        - name: Execute stat script on /etc/group-
          shell: /tmp/audit/stat-script 644 /etc/group-
          register: script_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if script_output.stdout == 'PASS' else 'Not Compliant' if script_output.stdout == 'FAIL' else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.4 | {{ compliance_status }}"

    - name: 6.1.5 Ensure permissions on /etc/shadow are configured
      block:
        - name: Execute stat script on /etc/shadow
          shell: /tmp/audit/stat-script 0 /etc/shadow
          register: script_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if script_output.stdout == 'PASS' else 'Not Compliant' if script_output.stdout == 'FAIL' else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.5 | {{ compliance_status }}"

    - name: 6.1.6 Ensure permissions on /etc/shadow- are configured
      block:
        - name: Execute stat script on /etc/shadow-
          shell: /tmp/audit/stat-script 0 /etc/shadow-
          register: script_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if script_output.stdout == 'PASS' else 'Not Compliant' if script_output.stdout == 'FAIL' else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.6 | {{ compliance_status }}"

    - name: 6.1.7 Ensure permissions on /etc/gshadow are configured
      block:
        - name: Execute stat script on /etc/gshadow
          shell: /tmp/audit/stat-script 0 /etc/gshadow
          register: script_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if script_output.stdout == 'PASS' else 'Not Compliant' if script_output.stdout == 'FAIL' else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.7 | {{ compliance_status }}"

    - name: 6.1.8 Ensure permissions on /etc/gshadow- are configured
      block:
        - name: Execute stat script on /etc/gshadow-
          shell: /tmp/audit/stat-script 0 /etc/gshadow-
          register: script_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if script_output.stdout == 'PASS' else 'Not Compliant' if script_output.stdout == 'FAIL' else 'Unknown' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.8 | {{ compliance_status }}"

    - name: 6.1.9 Ensure no world writable files exist
      block:
        - name: Check filesystems
          shell: df -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type f -perm -0002
          register: df_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if df_output.stdout == '' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.9 | {{ compliance_status }}"

    - name: 6.1.10 Ensure no unowned files or directories exist
      block:
        - name: Check filesystems
          shell: df -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser
          register: df_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if df_output.stdout == '' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.10 | {{ compliance_status }}"

    - name: 6.1.11 Ensure no ungrouped files or directories exist
      block:
        - name: Check filesystems
          shell: df -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -nogroup
          register: df_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if df_output.stdout == '' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.11 | {{ compliance_status }}"

    - name: 6.1.12 Ensure sticky bit is set on all world-writable directories
      block:
        - name: Check filesystems
          shell: df -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
          register: df_output

        - name: Set compliance status
          set_fact:
            compliance_status: "{{ 'Compliant' if df_output.stdout == '' else 'Not Compliant' }}"

        - name: Log to file
          include_tasks: ../logging.yml
          vars:
            status: "6.1.12 | {{ compliance_status }}"